# Site
repository: ajjacobs/homepage
#favicon: images/favicon.ico

# Personal info
name: Andrew Jacobsen
title: PhD Student
email: see most-recent publication
website: ajjacobs.github.io

# Social links
github_username:  ajjacobs

# About Section
# about_title: About Me
#about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a PhD student at the University of Alberta, supervised by Adam White and Martha White.
  I'm interested in Online Learning, Reinforcement Learning, Time-varying optimization, and Bandits.

# Projects Section
projects_title: Publications

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs
#Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#- Rock climbing
#- Gaming
#- Knitting
#- [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
